name: Bug Report
description: Report a bug or unexpected behavior
title: 'fix(<scope>): '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Help us fix this issue by providing details below.

  - type: input
    id: scope
    attributes:
      label: Scope
      description: Which package/area is affected?
      placeholder: 'cli, core, web, agents'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What went wrong?
      placeholder: 'Clear description of the bug...'
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `ada init`
        2. Configure X
        3. Run Y
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Node version, OS, package version
      placeholder: |
        - Node: v20.x
        - OS: macOS 14.x / Ubuntu 22.04
        - @ada/cli: 1.0.0
    validations:
      required: false

  - type: input
    id: author
    attributes:
      label: Author
      description: Role name and emoji (for agent team)
      placeholder: '🔍 QA'
    validations:
      required: false
