/**
 * @ada-ai/core — Reflexion Phase 2 Types
 *
 * Types for pattern extraction from reflection history.
 * Implements keyword clustering and confidence scoring per Shinn et al. (2023).
 *
 * @see docs/frontier/reflexion-phase2-impl-spec-c469.md
 */

import type { RoleId } from '../types.js';

// ─── Keyword Extraction ──────────────────────────────────────────────────────

/**
 * Keyword extracted from a reflection with optional role tag.
 * Used for TF-IDF weighting and cross-role pattern detection.
 */
export interface ExtractedKeyword {
  /** The keyword term (lowercase, normalized) */
  term: string;
  /** Weight based on TF-IDF or frequency */
  weight: number;
  /** Role tag for cross-role detection (e.g., "engineering") */
  roleTag?: RoleId;
}

// ─── Clustering ──────────────────────────────────────────────────────────────

/**
 * A cluster of reflections sharing similar keywords.
 * Generated by agglomerative clustering with Jaccard similarity.
 */
export interface ReflectionCluster {
  /** Unique cluster identifier */
  id: string;
  /** Top 3-5 representative keywords for this cluster */
  keywords: string[];
  /** Cycle IDs of reflections in this cluster (e.g., ["C450", "C463"]) */
  reflectionIds: string[];
  /** Distribution of roles in the cluster (e.g., { engineering: 5, qa: 3 }) */
  roleDistribution: Record<string, number>;
  /** Total number of reflections in the cluster */
  size: number;
  /** Number of reflections within the recent cycle window */
  recentCount: number;
  /** Cohesion score: average pairwise similarity (0-1) */
  cohesion: number;
}

// ─── Pattern Detection ───────────────────────────────────────────────────────

/** Status of a detected pattern in the approval workflow */
export type PatternStatus = 'candidate' | 'accepted' | 'rejected';

/**
 * A detected pattern with confidence scoring.
 * Patterns above the confidence threshold can generate lesson suggestions.
 */
export interface ReflexionPattern {
  /** Unique pattern identifier (UUID) */
  id: string;
  /** Human-readable pattern theme (derived from top keywords) */
  theme: string;
  /** Description of what this pattern represents */
  description: string;
  /** Keywords associated with this pattern */
  keywords: string[];
  /** Confidence score (0.0 - 1.0), threshold 0.7 per Reflexion paper */
  confidence: number;
  /** Source cluster this pattern was derived from */
  sourceCluster: ReflectionCluster;
  /** Whether this pattern involves 2+ roles */
  crossRole: boolean;
  /** Roles involved in this pattern */
  roles: string[];
  /** Draft lesson text (generated suggestion) */
  suggestedLesson?: string;
  /** Approval status */
  status: PatternStatus;
  /** Unix timestamp when pattern was detected */
  detectedAt: number;
}

// ─── Configuration ───────────────────────────────────────────────────────────

/** Supported pattern extraction methods */
export type ExtractionMethod = 'keyword' | 'hybrid';

/**
 * Configuration for pattern extraction.
 * Sensible defaults per Reflexion paper (Shinn et al. 2023).
 */
export interface PatternExtractionConfig {
  /** Extraction method: 'keyword' (TF-IDF) or 'hybrid' (with embeddings) */
  method: ExtractionMethod;
  /** Confidence threshold for pattern acceptance (default: 0.7) */
  confidenceThreshold: number;
  /** Minimum cluster size to form a pattern (default: 3) */
  minClusterSize: number;
  /** Window for "recent" reflections in cycles (default: 50) */
  recentCycleWindow: number;
  /** Maximum patterns to return (default: 10) */
  maxPatterns: number;
}

// ─── Input Types ─────────────────────────────────────────────────────────────

/**
 * Reflection data required for pattern extraction.
 * Simplified view of RotationHistoryEntry with required fields.
 */
export interface ReflectionInput {
  /** Cycle identifier (e.g., "C450" or "450") */
  cycle: string;
  /** Role that generated this reflection */
  role: RoleId;
  /** The "what worked" text to analyze */
  whatWorked: string;
  /** Optional: lesson learned text for additional keywords */
  lessonLearned?: string;
}
